# Generated by Django 5.0.6 on 2024-07-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_facerecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="facerecord",
            name="additional_info",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
