# Generated by Django 5.0.6 on 2024-07-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_facerecord_additional_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facerecord",
            name="image",
            field=models.ImageField(upload_to="static/faces/"),
        ),
    ]
